#!/bin/bash

set -eu -o pipefail

if [[ $# != 1 ]]; then
  echo "USAGE: $(basename $0) [image_to_compare]"
  exit 1
fi

docker pull $1
image_one_tgz="$(mktemp)"
docker save $1 -o "${image_one_tgz}"
image_one="$(mktemp -d)"
tar xzf "${image_one_tgz}" -C "${image_one}"
image_one_file_list="$(mktemp)"
for file in ${image_one}/*/layer.tar; do tar tf "$file"; done | sort | uniq > "${image_one_file_list}"

tiny_tgz="$(mktemp)"
docker save tiny -o "${tiny_tgz}"
tiny="$(mktemp -d)"
tar xzf "${tiny_tgz}" -C "${tiny}"
tiny_file_list="$(mktemp)"
for file in ${tiny}/*/layer.tar; do tar tf $file; done | awk '{print "./"$1}' | sort | uniq > "${tiny_file_list}"

nvim -d "${image_one_file_list}" "${tiny_file_list}"

rm -rf "${image_one}" "${image_one_file_list}" "${tiny}" "${tiny_file_list}" \
  "${image_one_tgz}" "${tiny_tgz}"
