#!/usr/bin/env bash

set -euo pipefail

generate_diff() {
  local prev_tag=$1
  local receipt=$2

  git diff "${prev_tag}" "${receipt}" \
    | grep -v "^---" \
    | grep -v "^+++" \
    | grep -e "^+" -e "^-" \
    || true
}

escape() {
  s=$1
  s="${s//'%'/'%25'}"
  s="${s//$'\n'/'%0A'}"
  s="${s//$'\r'/'%0D'}"
  echo "${s}"
}

main() {
  local user=$1
  local token=$2

  previous_tag="$(git tag --sort version:refname | tail -n 1)"

  run_diff="$(generate_diff "${previous_tag}" run-receipt)"
  echo "::set-output name=run_diff::$(escape "${run_diff}")"

  build_diff="$(generate_diff "${previous_tag}" build-receipt)"
  echo "::set-output name=build_diff::$(escape "${build_diff}")"
}

main "$@"
