name: Test create stack

on:
  workflow_dispatch: { }
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/test-create-stack.yml'
      - 'arch/**'
      - 'bionic/**'
      - 'create-stack/**'
      - 'packages/**'
      - 'tiny/**'

jobs:
  test-create-stack:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Docker login
        run: |
          docker login -u ${{ secrets.PAKETO_TESTING_DOCKERHUB_USERNAME }} --password-stdin \
            < <(echo '${{ secrets.PAKETO_TESTING_DOCKERHUB_PASSWORD }}')

      - name: Run Tests
        run: |
          cd create-stack
          go test ./...

          cd test/acceptance
          go test -timeout 30m ./...

  upload:
    name: Upload Workflow Event Payload
    runs-on: ubuntu-latest
    steps:
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: event-payload
        path: ${{ github.event_path }}
